os: linux
language: android

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support

jdk: oraclejdk8
sudo: false

addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
      - curl
before_script:
  # Execute ApolloTV prebuild webhook.
  - ./.travis/prebuild.sh $WEBHOOK_URL
  # Setup gradle.
  - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
  - unzip -qq gradle-3.5-bin.zip
  # Set SDK and PATH variables.
  - export ANDROID_SDK_ROOT=$PWD/android-sdk
  - export ANDROID_HOME=$PWD/android-sdk
  - export GRADLE_HOME=$PWD/gradle-3.5
  - export PATH=$GRADLE_HOME/bin:$ANDROID_HOME:$PATH
  # Clone Flutter
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1
script:
  # Run Flutter build
  - ./flutter/bin/flutter -v build apk
after_success:
  - ./.travis/postbuild.sh success $WEBHOOK_URL
after_failure:
  - ./.travis/postbuild.sh failure $WEBHOOK_URL

cache:
  directories:
    - $HOME/.pub-cache
