os: linux

env:
  - JOB_NAME="Kamino (Android)"
  global:
    - ANDROID_SDK_ROOT=/opt/android

jdk: oraclejdk8
sudo: required

addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - lib32stdc++6 # https://github.com/flutter/flutter/issues/6207
      - libstdc++6
      - fonts-droid
      - curl

before_script:
  # Execute ApolloTV prebuild webhook.
  - ./.travis/prebuild.sh $WEBHOOK_URL
  # Setup gradle.
  - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
  - unzip -qq gradle-3.5-bin.zip
  - export GRADLE_HOME=`pwd`/gradle-3.5
  - export PATH=$GRADLE_HOME/bin:$PATH
  # Setup Android SDK tools.
  - mkdir -p $ANDROID_SDK_ROOT
  - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "tools" "build-tools;28.0.3" "extras;android;m2repository" # android-28
  - export PATH=${ANDROID_SDK_ROOT}/tools/bin:$PATH
  # Clone Flutter
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH

script:
  # Run Flutter build
  - ./flutter/bin/flutter -v build apk

after_success:
  - ./.travis/postbuild.sh success $WEBHOOK_URL
after_failure:
  - ./.travis/postbuild.sh failure $WEBHOOK_URL

cache:
  directories:
    - $HOME/.pub-cache
